# Numpy Code Challenge

### Selecting Even Indices

In this practice challenge, we ask you to create an ndarray from a given list and select the values located at even indexes.

values = [7, 4, 5, 8, 9, 0, 1, 3, 2, 6]

In [2]:
import numpy as np
values = [7, 4, 5, 8, 9, 0, 1, 3, 2, 6]
values_arr = np.array(values)
print(values_arr)

[7 4 5 8 9 0 1 3 2 6]


### Selecting Odd Indices

In this practice challenge, we ask you to create an ndarray from a given list and select the values located at odd indexes.

values = [7, 4, 5, 8, 9, 0, 1, 3, 2, 6]

In [4]:
print(values_arr[1::2])

[4 8 0 3 6]


### Reversing an Ndarray

In this practice challenge, we ask you create an ndarray from a given list and to reverse the order of its values.

values = [7, 4, 5, 8, 9, 0, 1, 3, 2, 6]

In [5]:
print(values_arr[::-1])

[6 2 3 1 0 9 8 5 4 7]


### Getting the First Half

Write a function first_half() that, given a 1-dimensional array, returns an ndarray that contains the first half of the provided ndarray. If the input ndarray has an odd number of elements, you should exclude the middle element.

##### Testing Code
x = np.array([1, 2, 3, 4])
print(first_half(x))

x = np.array([1, 2, 3, 4, 5])
print(first_half(x))

In [12]:
def first_half(x):
    '''
    Returns an ndarray that contains the first half of the provided ndarray.
    If the input ndarray has an odd number of elements, the middle element is excluded.
    
    Keyword arguments
    x -- ndarray
    '''
    end_index = len(x)//2
    first_half_arr = x[:end_index]
    return first_half_arr

x = np.array([1, 2, 3, 4, 5])
print(first_half(x))


[1 2]


### Getting the Second Half

Write a function second_half() that, given a 1-dimensional array, returns an ndarray containing the second half of the provided ndarray. If the input ndarray has an odd number of elements, you should include the middle element.

##### Testing Code
x = np.array([1, 2, 3, 4])
print(first_half(x))

x = np.array([1, 2, 3, 4, 5])
print(first_half(x))

In [15]:
def second_half(x):
    '''
    Returns an ndarray that contains the second half of the provided ndarray.
    If the input ndarray has an odd number of elements, the middle element is included.
    
    Keyword arguments   
    x -- ndarray
    '''
    start_index = len(x)//2
    second_half_arr = x[start_index:]
    return second_half_arr

x = np.array([1, 2, 3, 4, 5])
print(second_half(x))



[3 4 5]


### Concatenating Ndarrays

Use the np.concatenate() function to concatenate two ndarrays from the sequence below.

values1 = [5, 7, 4, 6, 3, 9]
values2 = [2, 1, 8, 0]

In [17]:
values1 = [5, 7, 4, 6, 3, 9] 
values2 = [2, 1, 8, 0]
concatenated_arr = np.concatenate((values1, values2), axis=0)
print(concatenated_arr)

[5 7 4 6 3 9 2 1 8 0]


### Mixing Ndarrays

Write a function mix() that, given two 1-dimensional arrays x and y, produces a new ndarray where:

1. The first half of its values corresponds to the first half of x (excluding the middle element if x has an odd length).

2. The second half of its values corresponds to the second half of y (including the middle element if y has an odd length).

##### Testing Code
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 8, 9, 10])
z = mix(x, y)
print(z)

In [22]:
def mix(x, y):
    '''
    Returns a concatenated ndarray that contains the first half of an ndarray x 
    and the second half of an nd array y.
    
    Keyword arguments
    x -- an ndarray from which the first half will be extracted
    y -- an ndarray from which the second half will be extracted
    '''
    final_arr = np.concatenate((first_half(x), second_half(y)), axis = 0)
    return (final_arr)

x = np.array([1, 2, 3, 4, 5]) 
y = np.array([6, 7, 8, 9, 10])
z = mix(x, y)
print(z)

[ 1  2  8  9 10]


### Reverse and Skip

In this practice challenge, we ask you to reverse the values of a 1-dimensional ndarray below while skipping every other value.

For example, if the ndarray is [1 2 3 4 5 6 7] then you need to obtain [7 5 3 1].

values = [7, 4, 5, 8, 9, 0, 1, 3, 2, 6]

In [24]:
print(values_arr[::-2])

[6 3 0 8 4]


### Reversing a 2-D Array

In this practice challenge we want you to reverse a 2-dimensional ndarray. In other words, we want to obtain an ndarray where both the rows and the columns are in reverse order.

values = [
    [5, 6, 5, 5, 8, 9, 9], 
    [9, 5, 1, 4, 5, 9, 7], 
    [3, 9, 6, 2, 1, 2, 3], 
    [1, 7, 6, 7, 1, 7, 5], 
    [2, 1, 3, 8, 7, 8, 8], 
    [2, 9, 3, 6, 4, 6, 4]
]

In [36]:
values = [ [5, 6, 5, 5, 8, 9, 9], [9, 5, 1, 4, 5, 9, 7], [3, 9, 6, 2, 1, 2, 3], [1, 7, 6, 7, 1, 7, 5], [2, 1, 3, 8, 7, 8, 8], [2, 9, 3, 6, 4, 6, 4] ]
values2d_arr = np.array(values)
print(values2d_arr)
rev_values2d_arr = np.flip(values2d_arr)
print(rev_values2d_arr)

[[5 6 5 5 8 9 9]
 [9 5 1 4 5 9 7]
 [3 9 6 2 1 2 3]
 [1 7 6 7 1 7 5]
 [2 1 3 8 7 8 8]
 [2 9 3 6 4 6 4]]
[[4 6 4 6 3 9 2]
 [8 8 7 8 3 1 2]
 [5 7 1 7 6 7 1]
 [3 2 1 2 6 9 3]
 [7 9 5 4 1 5 9]
 [9 9 8 5 5 6 5]]


### Row Selection

In this practice challenge, you'll write a function select_rows() that given a 2-dimensional array and a list of row indexes, returns a 2-dimensional array consisting only of those rows.

##### Testing Code
x = np.array([[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
rows_1_4_3 = select_rows(x, [1, 4, 3])
print(rows_1_4_3)

In [40]:
def select_rows(x, a):
    '''
    Returns a 2-dimensional array consisting of selected rows from a 2d array

    Keyword arguments
    x -- a 2d array
    a -- a list containing row indexes
    '''
    sliced_rows = []
    for i in a:
        sliced_rows.append(x[i])
    return np.array(sliced_rows)

x = np.array([[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
rows_1_4_3 = select_rows(x, [1, 4, 3])
print(rows_1_4_3)



[[ 5  6  7  8]
 [17 18 19 20]
 [13 14 15 16]]


### Column Selection

In this practice challenge, you'll write a function select_columns() that given a 2-dimensional array and a list of column indexes, returns a 2-dimensional array consisting only of those columns.

##### Testing Code

x = np.array([[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
cols_3_0 = select_columns(x, [3, 0])
print(cols_3_0)

In [112]:
def select_columns(x, a):
    '''
    Returns a 2d array of a selected columns from a larger 2d array

    Keyword arguments
    x -- 2d array from which slicing is done
    a -- a list of column indexes
    '''
    sliced_columns = []
    for i in a:
        sliced_columns.append(x[:, i:i+1])
    return np.hstack(sliced_columns)

x = np.array([[ 1, 2, 3, 4], [ 5, 6, 7, 8], [ 9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
cols_3_0 = select_columns(x, [3, 0]) 
print(cols_3_0)

[[ 4  1]
 [ 8  5]
 [12  9]
 [16 13]
 [20 17]]


### Row Copies

In this practice challenge, you'll write a function copy_row_k_times() that given a 2-dimensional array, a row index row_index and a positive integer num_copies, creates a ndarray containing num_copies copies of row index row_index.
See the following example for clarity:

x = np.array([
    [ 1,  2,  3,  4], 
    [ 5,  6,  7,  8], 
    [ 9, 10, 11, 12]
])
row_k_times = copy_row_k_times(x, 1, 4)
print(row_k_times)

[[5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]
 
As you can see, this function created 4 copies for the row from x that has with index 1

##### Testing code

x = np.array([[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12]])
row_k_times = copy_row_k_times(x, 1, 4)
print(row_k_times)

In [122]:
def copy_row_k_times(x, y, z):
    '''
    Returns an ndarray containing copies of a sliced row from a parent array

    Keyword arguments
    x -- parent array
    y -- row index
    z -- a positive integer representing the number of copies of the row
    '''
    sliced_row = x[y]
    repititions = 4
    final_array = np.tile(sliced_row, (repititions, 1))
    return final_array
    
x = np.array([[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12]])
row_k_times = copy_row_k_times(x, 1, 4)
print(row_k_times)


[[5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]


### Selecting from a 2-D Array 1

In this practice challenge, we want you to select the entries highlighted in green of a 2-dimensional array.

![Image1](https://drive.google.com/file/d/1ujphPiOUtAZO73wzTidYcS7HCBBqNlBo/view?usp=sharing)

array2d = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
])

In [133]:
array2d = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
])

x = select_columns(array2d, [1, 2])
print('x =')
print(x)

print('------------------------------')
y = select_rows(array2d, [0, 2])
print('y =')
print(y)

print('------------------------------')
print('z =')
z = array2d[2][1:-1]
print(z)

x =
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]
------------------------------
y =
[[ 1  2  3  4  5]
 [11 12 13 14 15]]
------------------------------
z =
[12 13 14]


### Selecting from a 2-D Array 2

In this practice challenge, we want you to select the entries highlighted in green of a 2-dimensional array.

![Image2](https://drive.google.com/file/d/1GTFFw9vCSCPvR85sROK3pKtsh3tgzfDC/view?usp=sharing)

array2d = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
])


In [145]:
array2d = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
])

print(array2d)
sliced_arr = select_columns(array2d, [0, 2, 4])
x = select_rows(sliced_arr, [1, 3])
print('x =')
print(x)

print('------------------------------')
sliced_arr = select_columns(array2d, [1, 3])
y = select_rows(sliced_arr, [0, 2])
print('y =')
print(y)

print('------------------------------')
print('z =')
sliced_arr = select_columns(array2d, [1, 2, 3])
z = select_rows(sliced_arr, [0, 2])
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
x =
[[ 6  8 10]
 [16 18 20]]
------------------------------
y =
[[ 2  4]
 [12 14]]
------------------------------
z =
[[ 2  3  4]
 [12 13 14]]


### Selecting from a 2-D Array 3

In this practice challenge, we want you to select the entries highlighted in green of a 2-dimensional array.

![Image3](https://drive.google.com/file/d/1Gq6flsy7oFWysmApTfqAjfNasLBNMbr9/view?usp=sharing)

array2d = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
])


In [149]:
array2d = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
])

x = array2d[:, 2:]
print('x =')
print(x)
print('------------------------------')

sliced_arr = array2d[:, 1:]
y = select_rows(sliced_arr, range(1, 4))
print('y =')
print(y)
print('------------------------------')

sliced_arr = array2d[:, 1:]
z = select_rows(sliced_arr, range(0,3))
print('z =')
print(z)


x =
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]
 [18 19 20]]
------------------------------
y =
[[ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]]
------------------------------
z =
[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]


### Swapping Rows

In this practice challenge, we want you to write a function swap_rows() that given a 2-dimensional array and two row indexes, swaps those two rows.

Example:

x = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12]
])
swap_rows(x, 0, 1)
print(x)

[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
 
 Note that the function does not return anything, it modifies the given ndarray directly.
 
 ##### Testing Code
 
 x = np.array([[1,  2,  3,  4], [5,  6,  7,  8], [9, 10, 11, 12]])
swap_rows(x, 0, 2)
print(x)

In [151]:
def swap_rows(x, y, z):
    '''
    Returns a swapped rows of a 2d array

    Keyword arguments
    x -- 2d array 
    y -- positive integer representing the index of the row to be swapped
    z -- positive integer representing the index of the row to be swapped
    '''
    copy_x = x.copy()
    x[y] = copy_x[z]
    x[z] = copy_x[y]
    return x

x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x = swap_rows(x, 0, 2)
print(x)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


### Swapping Columns

In this practice challenge, we want you to write a function swap_cols() that given a 2-dimensional array and two column indexes, swaps those two columns.

Example:

x = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12]
])
swap_cols(x, 0, 1)
print(x)

[[ 2  1  3  4]
 [ 6  5  7  8]
 [10  9 11 12]]
 
Note that the function does not return anything, it modifies the given ndarray directly.

##### Testing Code

x = np.array([[1,  2,  3,  4], [5,  6,  7,  8], [9, 10, 11, 12]])
swap_cols(x, 0, 1)
print(x)


In [155]:
def swap_cols(x, y, z):
    '''
    Returns a swapped rows of a 2d array

    Keyword arguments
    x -- 2d array 
    y -- positive integer representing the index of the column to be swapped
    z -- positive integer representing the index of the column to be swapped
    '''
    copy_x = x.copy()
    x[:,y:y+1] = copy_x[:, z:z+1]
    x[:,z:z+1] = copy_x[:, y:y+1]
    return x

x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x = swap_cols(x, 0, 1)
print(x)

[[ 2  1  3  4]
 [ 6  5  7  8]
 [10  9 11 12]]
