# Numpy Boolean Masks Code Challenge

### Extracting All Even Values

In this practice problem, we want you to extract all even values from a 2-dimensional array. The result should be a 1-dimensional array that contains all even values of the provided 2-dimensional array.

x = np.array([
    [6, 8, 9, 4, 4], 
    [8, 1, 5, 3, 10], 
    [2, 6, 7, 6, 6], 
    [7, 8, 3, 6, 7], 
    [10, 7, 7, 5, 2]
])

In [18]:
import numpy as np
x = np.array([ [6, 8, 9, 4, 4], [8, 1, 5, 3, 10], [2, 6, 7, 6, 6], [7, 8, 3, 6, 7], [10, 7, 7, 5, 2] ])

even_values = x[x%2 == 0]
print(even_values)

[ 6  8  4  4  8 10  2  6  6  6  8  6 10  2]


### Extracting All Odd Values

In this practice problem, we want you to extract all odd values from a 2-dimensional array. The result should be a 1-dimensional array that contains all even values of the provided 2-dimensional array.

x = np.array([
    [6, 8, 9, 4, 4], 
    [8, 1, 5, 3, 10], 
    [2, 6, 7, 6, 6], 
    [7, 8, 3, 6, 7], 
    [10, 7, 7, 5, 2]
])

In [19]:
odd_values = x[x%2 == 1]
print(odd_values)

[9 1 5 3 7 7 3 7 7 7 5]


### Extracting Positive Values

In this practice problem, we want you to extract all positive values from a 2-dimensional array. The result should be a 1-dimensional array that contains all positive values of the provided 2-dimensional array.

x = np.array([
    [-6, 8, -9, 4, -4], 
    [8, -1, 5, 3, 10], 
    [2, 6, 7, 6, -6], 
    [7, -8, 3, -6, 7], 
    [10, -7, 7, -5, 2]
])

In [22]:
x = np.array([ [-6, 8, -9, 4, -4], [8, -1, 5, 3, 10], [2, 6, 7, 6, -6], [7, -8, 3, -6, 7], [10, -7, 7, -5, 2] ])
positive_values = x[x > 0]
print(positive_values)

[ 8  4  8  5  3 10  2  6  7  6  7  3  7 10  7  2]


### Extracting Negative Values

In this practice problem, we want you to extract all negative values from a 2-dimensional array. The result should be a 1-dimensional array that contains all negative values of the provided 2-dimensional array. 

x = np.array([
    [-6, 8, -9, 4, -4], 
    [8, -1, 5, 3, 10], 
    [2, 6, 7, 6, -6], 
    [7, -8, 3, -6, 7], 
    [10, -7, 7, -5, 2]
])

In [25]:
negative_values = x[x < 0]
print(negative_values)

[-6 -9 -4 -1 -6 -8 -6 -7 -5]


9

### Counting Values

In this practice problem, we want you to write a count_values() function given an ndarray, returns how many negative, zero, and positive values it contains.

Example:

x = np.array([
    [2, 0, -1, 3],
    [-5, 1, 0, 4],
    [7, 0, 0, -1]
])
print(count_values(x))

Result:

(3, 4, 5)

The 3 indicates the number of negative values, the 4 indicates the number of zeros, and the 5 indicates the number of positive values. The value counts should be returned in this order

##### Testing Code
#x = np.array([[2, 0, -1, 3], [-5, 1, 0, 4], [7, 0, 0, -1]])
#print(count_values(x))

In [27]:
def count_values(x):
    '''
    Counts the number of negative, zero and positive values contained in a given array
    Returns (neg, zero,pos) where neg = number of negative values, zero = number of zeros and pos = number of positive values
    
    Keyword arguments
    x -- an ndarray
    '''
    neg = len(x[x < 0])
    zero = len(x[x == 0])
    pos = len(x[x > 0])
    
    return (neg, zero, pos)


x = np.array([[2, 0, -1, 3], [-5, 1, 0, 4], [7, 0, 0, -1]])
print(count_values(x))
    

(3, 4, 5)


### Selecting Rows by Sum

In this practice problem, we want you to select all rows from a given 2-dimensional array whose sum is larger than 30.

x = np.array([
    [6, 8, 9, 4, 4], 
    [8, 1, 5, 3, 10], 
    [2, 6, 7, 6, 6], 
    [7, 8, 3, 6, 7], 
    [10, 7, 7, 5, 2]
])

In [47]:
x = np.array([ [6, 8, 9, 4, 4], [8, 1, 5, 3, 10], [2, 6, 7, 6, 6], [7, 8, 3, 6, 7], [10, 7, 7, 5, 2] ])

for i in x:
    if sum(i) > 30:
        print(i)

[6 8 9 4 4]
[7 8 3 6 7]
[10  7  7  5  2]


### Selecting Columns by Sum

In this practice problem, we want you to select all columns from a given 2-dimensional array whose sum is larger than 30.

x = np.array([
    [6, 8, 9, 4, 4], 
    [8, 1, 5, 3, 10], 
    [2, 6, 7, 6, 6], 
    [7, 8, 3, 6, 7], 
    [10, 7, 7, 5, 2]
])

In [81]:
a = x.shape[1] #The total number of columns
indexes = []
for i in range(a):
    if sum(x[:, i]) > 30:
        indexes.append(i)
    arr = x[:, indexes]

print(arr)

[[ 6  9]
 [ 8  5]
 [ 2  7]
 [ 7  3]
 [10  7]]


array([ 4, 10,  6,  7,  2])

## Selecting Perfect Squares

In mathematics, a perfect square is an integer number that is equal to the product of some other integer multiplied by itself.
For example, 25 is a perfect square because it is equal to 5 × 5. Another example is 100 since it is equal to 10 × 10.
In this practice problem, we provide you with a 1-dimensional array and want you to use a boolean mask to select all the perfect squares it contains.

Depending on your solution, you might find the numpy.sqrt() function useful. It calculates the square roots of values in an ndarray.

x = np.array([865, 395, 777, 912, 431, 42, 266, 989, 524, 498, 415, 941, 803, 850, 311, 992, 489, 367, 598, 914, 930, 224, 517, 143, 289, 144, 774, 98, 634, 819, 257, 932, 546, 723, 830, 617, 924, 151, 318, 102, 748, 76, 921, 871, 701, 339, 484, 574, 104, 363, 445, 324, 626, 656, 935, 210, 990, 566, 489, 454, 887, 534, 267, 64, 825, 941, 562, 938, 15, 96, 737, 861, 409, 728, 845, 804, 685, 641, 2, 627, 506, 848, 889, 342, 250, 748, 334, 721, 892, 65, 196, 940, 582, 228, 245, 823, 991, 146, 823, 557])

In [111]:
x = np.array([865, 395, 777, 912, 431, 42, 266, 989, 524, 498, 415, 941, 803, 850, 311, 992, 489, 367, 598, 914, 930, 224, 517, 143, 289, 144, 774, 98, 634, 819, 257, 932, 546, 723, 830, 617, 924, 151, 318, 102, 748, 76, 921, 871, 701, 339, 484, 574, 104, 363, 445, 324, 626, 656, 935, 210, 990, 566, 489, 454, 887, 534, 267, 64, 825, 941, 562, 938, 15, 96, 737, 861, 409, 728, 845, 804, 685, 641, 2, 627, 506, 848, 889, 342, 250, 748, 334, 721, 892, 65, 196, 940, 582, 228, 245, 823, 991, 146, 823, 557])
sqrt_x = np.sqrt(x)
sqrt_x_int = sqrt_x.astype(int)
perfect_squares = x[(sqrt_x_int * sqrt_x_int) == x]

print(perfect_squares)

[289 144 484 324  64 196]


### Finding Rows without zeros

In this practice problem, we provide you with a 2-dimensional array and we want you to extract all rows that do not contain any zero in them.

You might find the numpy.count_nonzero() function useful. This function also provides the axis keyword argument so that we can use it to calculate the number of zeros in each row or column.

x = np.array([
    [6, 8, 90, 0, 4], 
    [8, 0, 5, 3, 10], 
    [2, 6, 10, 6, 6], 
    [10, 8, 3, 6, 7], 
    [10, 7, 7, 0, 2]
])

In [162]:
x = np.array([ [6, 8, 90, 0, 4], [8, 0, 5, 3, 10], [2, 6, 10, 6, 6], [10, 8, 3, 6, 7], [10, 7, 7, 0, 2] ])
print(x)

nonzero_counts = np.count_nonzero(x, axis = 1)
nonzero_rows = x[nonzero_counts == x.shape[1]]
print(nonzero_rows)

[[ 6  8 90  0  4]
 [ 8  0  5  3 10]
 [ 2  6 10  6  6]
 [10  8  3  6  7]
 [10  7  7  0  2]]
[[ 2  6 10  6  6]
 [10  8  3  6  7]]


### Finding Rows with zeros

In this practice problem, we provide you with a 2-dimensional array and we want you to extract all rows that contain at least one zero.

x = np.array([
    [6, 8, 90, 0, 4], 
    [8, 0, 5, 3, 10], 
    [2, 6, 10, 6, 6], 
    [10, 8, 3, 6, 7], 
    [10, 7, 7, 0, 2]
])

In [161]:
nonzero_counts = np.count_nonzero(x, axis = 1)
zero_rows = x[nonzero_counts != x.shape[1]]
print(zero_rows)

[[ 6  8 90  0  4]
 [ 8  0  5  3 10]
 [10  7  7  0  2]]


### Finding Columns without zeros

In this practice problem, we provide you with a 2-dimensional array and we want you to extract all columns that do not contain any zero on them.

x = np.array([
    [6, 8, 90, 0, 4], 
    [8, 0, 5, 3, 10], 
    [2, 6, 10, 6, 6], 
    [10, 8, 3, 6, 7], 
    [10, 7, 7, 0, 2]
])

In [160]:
print(x)
nonzero_counts = np.count_nonzero(x, axis = 0)
nonzero_columns = x[:, (nonzero_counts == x.shape[0]).tolist()]
print(nonzero_columns)

[[ 6  8 90  0  4]
 [ 8  0  5  3 10]
 [ 2  6 10  6  6]
 [10  8  3  6  7]
 [10  7  7  0  2]]
[[ 6 90  4]
 [ 8  5 10]
 [ 2 10  6]
 [10  3  7]
 [10  7  2]]


### Finding Columns with zeros

In this practice problem, we provide you with a 2-dimensional array and we want you to extract all columns that contain at least one zero.

x = np.array([
    [6, 8, 90, 0, 4], 
    [8, 0, 5, 3, 10], 
    [2, 6, 10, 6, 6], 
    [10, 8, 3, 6, 7], 
    [10, 7, 7, 0, 2]
])

In [159]:
print(x)
nonzero_counts = np.count_nonzero(x, axis = 0)
zero_columns = x[:, (nonzero_counts != x.shape[0]).tolist()]
print(zero_columns)

print(nonzero_counts)

[[ 6  8 90  0  4]
 [ 8  0  5  3 10]
 [ 2  6 10  6  6]
 [10  8  3  6  7]
 [10  7  7  0  2]]
[[8 0]
 [0 3]
 [6 6]
 [8 6]
 [7 0]]
[5 4 5 3 5]


### Finding Perfect Grades

In this practice problem, we want you to write a function has_perfect_score() that given a 1-dimensional ndarray representing student grades between 0 and 100 (inclusive), returns whether any student had a grade equal to 100.

Example:

x = np.array([75, 67, 95, 100])
print(has_perfect_score(x))

Result:

True

Example:

x = np.array([75, 67, 95, 99])
print(has_perfect_score(x))

Result:

False

##### Testing Code
#x = np.array([75, 67, 95, 100])
#print(has_perfect_score(x))

#x = np.array([75, 67, 95, 99])
#print(has_perfect_score(x))

In [176]:
def has_perfect_score(x):
    '''
    Iterates through an 1-dimensional ndarray and and returns whether any student had a grade equal to 100

    Parameters
    x -- a 1-dimensional ndarray representing student grades between 0 and 100 (inclusive)
    '''
    return np.any(x == 100)

x = np.array([75, 67, 95, 100])
print(has_perfect_score(x))
x = np.array([75, 67, 95, 99])
print(has_perfect_score(x))

True
False


### Did Everyone Pass?

In this practice problem, we want you to write a function all_passed() that given a 1-dimensional ndarray representing student grades between 0 and 100 (inclusive), returns whether all students had a score of at least 50 or not.

Example:

x = np.array([75, 67, 95, 100])
print(all_passed(x))

Result:

True

In this case the answer is True because each score is greater than or equal to 50

Example:

x = np.array([75, 67, 45, 99])
print(all_passed(x))

Result:

False

In this case the answer is False because there is at least one score that is lower than 50.

##### Testing Code
#x = np.array([75, 67, 95, 100])
#print(all_passed(x))

#x = np.array([75, 67, 45, 99])
#print(all_passed(x))

In [177]:
def all_passed(x):
    '''
    Iterates through an 1-dimensional ndarray and and returns whether any student had a score of at least
    50 or not

    Parameters
    x -- a 1-dimensional ndarray representing student grades between 0 and 100 (inclusive)
    '''
    return np.all(x >= 50)

x = np.array([75, 67, 95, 100])
print(all_passed(x))
x = np.array([75, 67, 45, 99])
print(all_passed(x))

True
False


### Grade Categories

In this practice problem, we want you to write a function grade_category_count() that given a 1-dimensional ndarray representing student grades between 0 and 100 (inclusive), returns a dictionary that counts how many grades fall in each category.
The categories are letters A to F. For this problem, we use a simplification of the grade categories used in the USA.

| Category | Grade Range |
|----------|-------------|
| A        | 90 to 100   |
| B        | 80 to 89    |
| C        | 70 to 79    |
| D        | 65 to 69    |
| E        | 50 to 64    |
| F        | 0 to 49     |

Example:

x = np.array([75, 67, 95, 100])
print(grade_category_count(x))

Result:

{'A': 2, 'B': 0, 'C': 1, 'D': 1, 'E': 0, 'F': 0}

Example:

x = np.array([0, 49, 50, 64, 65, 69, 70, 79, 80, 89, 90, 100])
print(grade_category_count(x))

Result:

{'A': 2, 'B': 2, 'C': 2, 'D': 2, 'E': 2, 'F': 2}

##### Testing Code
#x = np.array([75, 67, 95, 100])
#print(grade_category_count(x))

#x = np.array([0, 49, 50, 64, 65, 69, 70, 79, 80, 89, 90, 100])
#print(grade_category_count(x))

In [201]:
def grade_category_count(x):
    '''
    Returns a dictionary that counts how many grades fall in each grade category as used in the USA
    
    Parameters
    x -- a 1-dimensional nd array representing student grades between 0 and 100 (inclusive)
    '''
    grade_cat = {'A': 0, 'B': 0, 'C': 0, 'D': 0, 'E': 0, 'F': 0}
    for i in x:
        if 90 <= i <= 100:
            grade_cat['A'] += 1
        elif 80 <= i <= 89:
            grade_cat['B'] += 1
        elif 70 <= i <= 79:
            grade_cat['C'] += 1
        elif 65 <= i <= 69:
            grade_cat['D'] += 1
        elif 50 <= i <= 64:
            grade_cat['E'] += 1
        elif 0 <= i <= 49:
            grade_cat['F'] += 1
            
    return grade_cat

x = np.array([0, 49, 50, 64, 65, 69, 70, 79, 80, 89, 90, 100])
print(grade_category_count(x))

{'A': 2, 'B': 2, 'C': 2, 'D': 2, 'E': 2, 'F': 2}


### Multiplying By Two

In this practice problem, we provide you with a 2-dimensional array and we want you to multiply each value that is smaller than 100 by 2.

x = np.array([
    [111, 48, 145, 196, 26], 
    [92, 122, 78, 157, 66], 
    [112, 173, 46, 110, 192], 
    [23, 58, 39, 186, 165], 
    [30, 67, 159, 11, 197], 
    [163, 180, 147, 103, 11], 
    [61, 6, 51, 73, 45]
])

In [217]:
x = np.array([ [111, 48, 145, 196, 26], [92, 122, 78, 157, 66], [112, 173, 46, 110, 192], [23, 58, 39, 186, 165], [30, 67, 159, 11, 197], [163, 180, 147, 103, 11], [61, 6, 51, 73, 45] ])
print(x)

x[x <= 100] = x[x <= 100] * 2

print(x)

[[111  48 145 196  26]
 [ 92 122  78 157  66]
 [112 173  46 110 192]
 [ 23  58  39 186 165]
 [ 30  67 159  11 197]
 [163 180 147 103  11]
 [ 61   6  51  73  45]]
[[111  96 145 196  52]
 [184 122 156 157 132]
 [112 173  92 110 192]
 [ 46 116  78 186 165]
 [ 60 134 159  22 197]
 [163 180 147 103  22]
 [122  12 102 146  90]]


### Making It Even

In this practice problem, we provide you with a 2-dimensional array and we want you to turn every entry into an even number. To do so, entries that are already even should remain the same and you should increment by one each of the odd entry.

x = np.array([
    [111, 48, 145, 196, 26], 
    [92, 122, 78, 157, 66], 
    [112, 173, 46, 110, 192], 
    [23, 58, 39, 186, 165], 
    [30, 67, 159, 11, 197], 
    [163, 180, 147, 103, 11], 
    [61, 6, 51, 73, 45]
])

In [224]:
x = np.array([ [111, 48, 145, 196, 26], [92, 122, 78, 157, 66], [112, 173, 46, 110, 192], [23, 58, 39, 186, 165], [30, 67, 159, 11, 197], [163, 180, 147, 103, 11], [61, 6, 51, 73, 45] ])

x[x%2 == 1] = x[x%2 == 1] + 1

print(x)

[[112  48 146 196  26]
 [ 92 122  78 158  66]
 [112 174  46 110 192]
 [ 24  58  40 186 166]
 [ 30  68 160  12 198]
 [164 180 148 104  12]
 [ 62   6  52  74  46]]


### Partitioning By Index

In this practice problem, we want you to write a partition() function given a 1-dimensional array x and an index i returns two 1-dimensional arrays. The first one should contain the values of x that are smaller than or equal to x[i]. The second one should contain the values of x that are bigger than x[i].

Example:

x = np.array([5, 4, 3, 1, 2, 6])
print(partition(x, 1))

Result:

(array([4, 3, 1, 2]), array([5, 6]))

In the above example, we use index i = 1. Since x[1] is 4, the first ndarray contains the values that are less than or equal to 4 while the second ndarray contains the values that are bigger than 4. 

##### Testing Code
#x = np.array([5, 4, 3, 1, 2, 6])
#print(partition(x, 1))

In [232]:
def partition(x, i):
    '''
    Returns two 1-dimensional arrays; first is formed by the values of array x that are smaller than or 
    equal to x[i] and second formed by the values of x that are bigger than x[i]

    Parameters
    x -- a 1-dimensional array
    i -- an integer representing the index specified in the function where the partitioning is evaluated
    '''
    array_1 = x[x <= x[i]]
    array_2 = x[x > x[i]]
    return array_1, array_2 

x = np.array([5, 4, 3, 1, 2, 6])

print(partition(x, 1))

(array([4, 3, 1, 2]), array([5, 6]))


### Partitioning By Median

In this practice problem, we want you to write a partition_by_median() function given a 1-dimensional array x and returns two 1-dimensional arrays. The first one should contain the values of x that are smaller than or equal to the median of x. The second one should contain the values of x that are bigger than the median of x.

Example:

x = np.array([5, 4, 3, 1, 2, 6])
print(partition_by_median(x))

Result:

(array([3, 1, 2]), array([5, 4, 6]))

In the above example, the media is equal to 3.5.

##### Testing Code
#x = np.array([5, 4, 3, 1, 2, 6])
#print(partition_by_median(x))

In [235]:
def partition_by_median(x):
    '''
    Returns two 1-dimensional arrays; first is formed by the values of array x that are smaller than or 
    equal to the median and second formed by the values of x that are bigger than the median

    Parameters
    x -- a 1-dimensional array
    '''
    array_1 = x[x <= np.median(x)]
    array_2 = x[x > np.median(x)]
    return array_1, array_2 

x = np.array([5, 4, 3, 1, 2, 6])
print(partition_by_median(x))

(array([3, 1, 2]), array([5, 4, 6]))


### Removing Non-Integer Values

In this practice problem, we provide you with a 1-dimensional array and we want you to remove all of its values that are not whole numbers.

x = np.array([69, 11, 90.49457494755877, 24, 41.54767580801889, 20.12965860001413, 91, 8.907758419177767, 29.20435557818945, 8, 45.18320647101104, 62, 16.968544743478553, 40, 51, 68, 55.20359682954337, 62, 50.42464165922171, 87.27047049165729, 85, 55.52435761508429, 17, 12, 74, 87.07403786258838, 15, 45.609731039236806, 92, 76, 21, 63.8621099409078, 69.59406746317076, 72.80028174630625, 85.05847290039019, 28.358592338847522, 17.45367343314122, 2.153572543427297, 55, 44.357813470302936, 32.05250226743463, 58, 29.824086847791452, 37.91413490742849, 40.623640765035375, 56.51534195174339, 15, 47.739633378954096, 18.538416505563532, 59.81627771902749])

In [315]:
x = np.array([69, 11, 90.49457494755877, 24, 41.54767580801889, 20.12965860001413, 91, 8.907758419177767, 29.20435557818945, 8, 45.18320647101104, 62, 16.968544743478553, 40, 51, 68, 55.20359682954337, 62, 50.42464165922171, 87.27047049165729, 85, 55.52435761508429, 17, 12, 74, 87.07403786258838, 15, 45.609731039236806, 92, 76, 21, 63.8621099409078, 69.59406746317076, 72.80028174630625, 85.05847290039019, 28.358592338847522, 17.45367343314122, 2.153572543427297, 55, 44.357813470302936, 32.05250226743463, 58, 29.824086847791452, 37.91413490742849, 40.623640765035375, 56.51534195174339, 15, 47.739633378954096, 18.538416505563532, 59.81627771902749])

#Square the elements in x
x_sq = x * x
#print(x_sq)

#Convert elements in x to integers
int_x = x.astype(int)

#Square the elements in integered x
int_x_sq = int_x * int_x
#print(int_x_sq)

#Extract whole numbers
print(x[x_sq == int_x_sq])

[69. 11. 24. 91.  8. 62. 40. 51. 68. 62. 85. 17. 12. 74. 15. 92. 76. 21.
 55. 58. 15.]


### Exclusive OR

In this practice problem, we provide you with a 2-dimensional array with two columns. We want you to retrieve all rows so that exactly one of these conditions is true:

The value in the first column is smaller than 100

The value in the second column is bigger than 100

x = np.array([[118, 90], [50, 6], [149, 162], [160, 36], [55, 197], [188, 85], [194, 25], [1, 95], [84, 116], [198, 92], [56, 148], [37, 145], [78, 193], [47, 8], [3, 108], [23, 69], [44, 47], [70, 57], [54, 50], [20, 78]])

In [314]:
x = np.array([[118, 90], [50, 6], [149, 162], [160, 36], [55, 197], [188, 85], [194, 25], [1, 95], [84, 116], [198, 92], [56, 148], [37, 145], [78, 193], [47, 8], [3, 108], [23, 69], [44, 47], [70, 57], [54, 50], [20, 78]])

#Finding indexes in first and second column that evaluates true for the conditions
first_col = np.where(x[:, 0] < 100)[0].tolist()
second_col = np.where(x[:, 1] > 100)[0].tolist()

union = set(first_col).union(second_col)
intersect = set.intersection(set(first_col), set(second_col))
row_indexes = list(union.difference(intersect))
print(x[row_indexes])

[[ 50   6]
 [149 162]
 [  1  95]
 [ 47   8]
 [ 23  69]
 [ 44  47]
 [ 70  57]
 [ 54  50]
 [ 20  78]]
